#!/usr/bin/env python3
"""
ARC reference-client viewer — build step (stdlib only, self-contained).

What this is
------------
The first *visible* face of ARC. It is NOT a runtime and NOT an implementation:
it is a read-only viewer that renders the seven core client surfaces over a
single signed event log, to make one claim legible to a human eye —

    every surface is a projection over one closed event log.

Honest scope (deliberate)
-------------------------
  * The log is NOT authored here. It is generated by the real probe
    `examples/end-to-end-demo/flow.py` and reused verbatim — so what the viewer
    shows is real generated data, not a mock.
  * Read-only. No keys, no signing, no MCP, no live proposal. This viewer
    therefore does not touch the two questions we deliberately deferred —
    key custody, and cold-start vs unrooted. It shows a log; it does not make one.
  * The projections are computed by the probe's own fold
    (`project_merchant_standing`), not re-implemented here. The HTML is pure
    presentation; the authority over "what the log means" stays in the probe.
  * This demo's delegation is single-level (one per-purchase AUTHORIZE), so the
    delegation tree is shallow. Multi-level sub-agent spawning is out of scope
    for this log and is left for a later fixture.

Run:  python3 build.py    ->  writes client.html  (open it in a browser)
"""

from __future__ import annotations

import contextlib
import dataclasses
import html
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "end-to-end-demo"))

import flow  # the real probe; reused, not copied

# key id -> display name (presentation only; the keys come from flow.py's parties)
NAMES = {
    "k:human": "human",
    "k:consumer_agent": "consumer-agent",
    "k:merchant": "merchant-agent",
    "k:community": "community",
}


def name(key: str) -> str:
    return NAMES.get(key, key)


def esc(x) -> str:
    return html.escape(str(x))


# ---------------------------------------------------------------------------
# Capture the real generated log (suppress the probe's narration on import-run).
# ---------------------------------------------------------------------------

def capture_log() -> list[flow.Event]:
    with contextlib.redirect_stdout(io.StringIO()):
        ledger = flow.run()
    return ledger.events


def project_at(events: list[flow.Event], upto_predicate: str) -> dict:
    """Fold the log up to and including the first event with this predicate,
    using the probe's own projection (not re-implemented here)."""
    cut = next(i for i, e in enumerate(events) if e.predicate == upto_predicate)
    sub = events[: cut + 1]
    return flow.project_merchant_standing(sub, flow.MERCHANT, flow.CONTEXT)


# ---------------------------------------------------------------------------
# Surface renderers — each returns an HTML fragment, each sourced from the log.
# ---------------------------------------------------------------------------

def render_delegation_tree(events) -> str:
    keys = [e for e in events if e.type == "KEY" and e.predicate == "id.key_register"]
    auth = next(e for e in events if e.type == "AUTHORIZE")
    grantees = sorted({name(e.signer) for e in events if auth.id in e.refs})
    scope = auth.scope or {}
    scope_str = ", ".join(f"{k}={v}" for k, v in scope.items())

    rows = []
    for k in keys:
        nm = name(k.signer)
        rows.append(f'<div class="node"><span class="who">{esc(nm)}</span>'
                    f'<span class="kid">{esc(k.signer)}</span></div>')
        if nm == name(auth.signer):
            for g in grantees:
                rows.append(
                    f'<div class="edge">└─ AUTHORIZE <code>{esc(auth.predicate)}</code> '
                    f'→ <span class="who">{esc(g)}</span>'
                    f'<span class="scope">scope: {esc(scope_str)}</span></div>')
    note = ('<p class="note">Four independently key-rooted participants. The only '
            'delegation edge in this log is one per-purchase AUTHORIZE — '
            'single-level by design of this probe.</p>')
    return "".join(rows) + note


def render_mandate(events) -> str:
    auth = next(e for e in events if e.type == "AUTHORIZE")
    scope = auth.scope or {}
    rows = "".join(f'<div class="kv"><span>{esc(k)}</span><code>{esc(v)}</code></div>'
                   for k, v in scope.items())
    return (
        f'<div class="mandate">'
        f'<div class="kv"><span>granted by</span><code>{esc(name(auth.signer))}</code></div>'
        f'<div class="kv"><span>predicate</span><code>{esc(auth.predicate)}</code></div>'
        f'{rows}'
        f'<div class="kv"><span>refs</span><code>{esc(", ".join(auth.refs))}</code></div>'
        f'</div>'
        f'<p class="note">This is the boundary between what an agent may sign '
        f'<em>without re-asking</em> (in scope) and what must escalate.</p>')


def render_approval_inbox(events) -> str:
    auth = next(e for e in events if e.type == "AUTHORIZE")
    return (
        f'<div class="approval resolved">'
        f'<div class="head"><span class="tag ok">RESOLVED</span> '
        f'consumer-agent requested approval for an offer</div>'
        f'<div class="body">the consumer agent could not approve; the human '
        f'reviewed and signed <code>AUTHORIZE {esc(auth.predicate)}</code> '
        f'<span class="evid">[{esc(auth.id)}]</span></div>'
        f'</div>'
        f'<p class="note">The request itself is transport (a message), not a '
        f'stored event. Only the human\'s AUTHORIZE is on the log.</p>')


def render_commitments(events) -> str:
    preds = {"commerce.offer", "commerce.payment_result", "commerce.fulfillment"}
    items = []
    for e in events:
        if e.predicate in preds:
            summary = ", ".join(f"{k}={v}" for k, v in e.payload.items()
                                if k not in ("context",))
            items.append(
                f'<div class="commit"><div class="head">'
                f'<span class="who">{esc(name(e.signer))}</span> '
                f'<code>{esc(e.predicate)}</code> '
                f'<span class="evid">[{esc(e.id)}]</span></div>'
                f'<div class="body">{esc(summary)}</div></div>')
    return "".join(items)


def render_projection(snapshots) -> str:
    buttons, panels = [], []
    for i, (label, s) in enumerate(snapshots):
        active = " active" if i == 0 else ""
        buttons.append(
            f'<button class="snapbtn{active}" data-snap="{i}">{i+1}</button>')
        rows = (
            f'<div class="kv big"><span>governance_standing</span>'
            f'<code class="gov-{esc(s["governance_standing"])}">'
            f'{esc(s["governance_standing"])}</code></div>'
            f'<div class="kv"><span>advisory_signal</span>'
            f'<code>{esc(s["advisory_signal"])}</code></div>'
            f'<div class="kv"><span>open_disputes</span>'
            f'<code>{esc(s["open_disputes"])}</code></div>'
            f'<div class="kv"><span>outcomes</span>'
            f'<code>+{esc(s["positive_outcomes"])} / -{esc(s["negative_outcomes"])}</code></div>')
        panels.append(
            f'<div class="snap{active}" data-snap="{i}">'
            f'<div class="snaplabel">{esc(label)}</div>{rows}</div>')
    caption = ('<p class="note">Same fold, recomputed at three cuts of the same '
               'log. <strong>governance does not move on the dispute — only on the '
               'ADJUDICATE.</strong> Nothing is stored; each view is recomputed.</p>')
    return (f'<div class="snapnav">snapshot {"".join(buttons)}</div>'
            f'{"".join(panels)}{caption}')


def render_challenge(events) -> str:
    chal = next(e for e in events if e.type == "CHALLENGE")
    adj = next(e for e in events if e.type == "ADJUDICATE")
    return (
        f'<div class="challenge"><span class="tag warn">⚠ CHALLENGE</span> '
        f'<code>{esc(chal.predicate)}</code> by {esc(name(chal.signer))} '
        f'<span class="evid">[{esc(chal.id)}]</span><div class="body">'
        f'{esc(chal.payload.get("reason",""))}</div></div>'
        f'<div class="adjudication"><span class="tag verdict">⚖ ADJUDICATE</span> '
        f'<code>{esc(adj.predicate)}</code> by {esc(name(adj.signer))} '
        f'<span class="evid">[{esc(adj.id)}]</span><div class="body">'
        f'resolves <code>{esc(adj.payload.get("resolves",""))}</code></div></div>'
        f'<p class="note">A CHALLENGE opens a dispute; only an ADJUDICATE '
        f'(referencing it) resolves it and moves commons standing.</p>')


def render_event_log(events) -> str:
    rows = []
    for i, e in enumerate(events):
        rows.append(
            f'<tr data-i="{i}"><td>{i}</td><td class="t-{esc(e.type)}">{esc(e.type)}</td>'
            f'<td>{esc(name(e.signer))}</td><td><code>{esc(e.predicate)}</code></td>'
            f'<td class="evid">{esc(e.id)}</td></tr>')
    return ('<table class="log"><thead><tr><th>#</th><th>type</th><th>signer</th>'
            '<th>predicate</th><th>id</th></tr></thead><tbody>'
            + "".join(rows) + '</tbody></table>'
            '<div id="inspector"><div class="ins-empty">click an event to inspect '
            'its raw signed form</div></div>')


# ---------------------------------------------------------------------------
# Page assembly.
# ---------------------------------------------------------------------------

CSS = """
:root{--ink:#1d2330;--mut:#6b7280;--line:#e3e6ee;--bg:#f7f8fb;--card:#fff;
--ok:#15803d;--warn:#b45309;--verdict:#6d28d9;--accent:#1f4ed8}
*{box-sizing:border-box}body{margin:0;font:13px/1.5 ui-monospace,SFMono-Regular,
Menlo,Consolas,monospace;color:var(--ink);background:var(--bg)}
header{padding:14px 20px;border-bottom:1px solid var(--line);background:var(--card)}
header h1{margin:0;font-size:15px;letter-spacing:.02em}
header .sub{color:var(--mut);font-size:12px;margin-top:3px}
.grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px;padding:14px}
.col{display:flex;flex-direction:column;gap:14px}
.card{background:var(--card);border:1px solid var(--line);border-radius:8px;
overflow:hidden}
.card>h2{margin:0;padding:9px 12px;font-size:12px;letter-spacing:.04em;
text-transform:uppercase;color:var(--mut);border-bottom:1px solid var(--line);
background:#fbfcfe}
.card>.in{padding:12px}
.note{color:var(--mut);font-size:11.5px;margin:10px 0 0;line-height:1.45}
code{background:#f0f2f7;padding:1px 5px;border-radius:4px;font-size:12px}
.who{font-weight:600}.kid{color:var(--mut);margin-left:8px;font-size:11px}
.node{padding:3px 0}.edge{padding:3px 0 3px 16px;color:#374151}
.edge .scope{display:block;color:var(--mut);font-size:11px;padding-left:18px}
.kv{display:flex;justify-content:space-between;gap:10px;padding:4px 0;
border-bottom:1px dashed var(--line)}.kv:last-child{border:0}
.kv span{color:var(--mut)}.kv.big code{font-size:13px}
.approval,.commit,.challenge,.adjudication{border:1px solid var(--line);
border-radius:6px;padding:9px;margin-bottom:8px}
.approval .head,.commit .head{font-weight:600;margin-bottom:4px}
.body{color:#374151}.evid{color:var(--mut);font-size:11px}
.tag{font-size:10px;font-weight:700;padding:1px 6px;border-radius:10px;
letter-spacing:.05em}.tag.ok{background:#dcfce7;color:var(--ok)}
.tag.warn{background:#fef3c7;color:var(--warn)}
.tag.verdict{background:#ede9fe;color:var(--verdict)}
.snapnav{color:var(--mut);margin-bottom:10px}
.snapbtn{font:inherit;border:1px solid var(--line);background:#fff;width:26px;
height:26px;border-radius:6px;margin-left:5px;cursor:pointer}
.snapbtn.active{background:var(--accent);color:#fff;border-color:var(--accent)}
.snap{display:none}.snap.active{display:block}
.snaplabel{font-size:11.5px;color:var(--mut);margin-bottom:6px;font-style:italic}
.gov-in_good_standing{color:var(--ok)}.gov-warned{color:var(--warn)}
.full{padding:0 14px 18px}
table.log{width:100%;border-collapse:collapse;background:var(--card);
border:1px solid var(--line);border-radius:8px;overflow:hidden}
table.log th,table.log td{text-align:left;padding:6px 10px;
border-bottom:1px solid var(--line);font-size:12px}
table.log th{color:var(--mut);text-transform:uppercase;font-size:10.5px;
letter-spacing:.04em;background:#fbfcfe}
table.log tbody tr{cursor:pointer}table.log tbody tr:hover{background:#f3f6ff}
table.log tbody tr.sel{background:#e8efff}
.t-KEY{color:#475569}.t-ATTEST{color:#0369a1}.t-AUTHORIZE{color:#15803d}
.t-CHALLENGE{color:#b45309}.t-ADJUDICATE{color:#6d28d9}
#inspector{margin-top:10px;background:#0f172a;color:#e2e8f0;border-radius:8px;
padding:12px;font-size:11.5px;white-space:pre;overflow:auto;max-height:280px}
.ins-empty{color:#64748b}
"""

JS = """
const EVENTS = JSON.parse(document.getElementById('arc-data').textContent);
document.querySelectorAll('.snapbtn').forEach(b=>b.onclick=()=>{
  const i=b.dataset.snap;
  document.querySelectorAll('.snapbtn').forEach(x=>x.classList.toggle('active',x===b));
  document.querySelectorAll('.snap').forEach(p=>p.classList.toggle('active',p.dataset.snap===i));
});
document.querySelectorAll('table.log tbody tr').forEach(tr=>tr.onclick=()=>{
  document.querySelectorAll('table.log tbody tr').forEach(x=>x.classList.remove('sel'));
  tr.classList.add('sel');
  const e=EVENTS[+tr.dataset.i];
  document.getElementById('inspector').textContent=JSON.stringify(e,null,2);
});
"""


def build_html(events, snapshots) -> str:
    data = json.dumps([dataclasses.asdict(e) for e in events], default=list)
    card = lambda t, b: f'<div class="card"><h2>{t}</h2><div class="in">{b}</div></div>'
    left = card("delegation tree", render_delegation_tree(events)) + \
        card("mandate viewer", render_mandate(events))
    mid = card("approval inbox", render_approval_inbox(events)) + \
        card("signed commitments", render_commitments(events))
    right = card("projection viewer", render_projection(snapshots)) + \
        card("challenge / adjudication", render_challenge(events))
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ARC reference client (viewer)</title><style>{CSS}</style></head><body>
<header><h1>ARC reference client — read-only viewer</h1>
<div class="sub">{len(events)} signed events from <code>end-to-end-demo</code> ·
every panel below is a projection over the one log · no keys, no runtime</div></header>
<div class="grid">
<div class="col">{left}</div>
<div class="col">{mid}</div>
<div class="col">{right}</div>
</div>
<div class="full"><div class="card"><h2>event log — the one source of truth</h2>
<div class="in">{render_event_log(events)}</div></div></div>
<script id="arc-data" type="application/json">{data}</script>
<script>{JS}</script>
</body></html>"""


def main() -> None:
    events = capture_log()
    snapshots = [
        ("after fulfillment", project_at(events, "commerce.fulfillment")),
        ("after dispute", project_at(events, "rep.outcome")),
        ("after adjudication", project_at(events, "gov.warning")),
    ]
    out = os.path.join(HERE, "client.html")
    with open(out, "w") as f:
        f.write(build_html(events, snapshots))
    print(f"captured {len(events)} signed events from the end-to-end-demo probe")
    for label, s in snapshots:
        print(f"  [{label}] governance={s['governance_standing']} "
              f"open_disputes={s['open_disputes']}")
    print(f"wrote {os.path.relpath(out)} — open it in a browser")


if __name__ == "__main__":
    main()
