#!/usr/bin/env python3
"""
ARC reference-client viewer — build step (stdlib only, self-contained).

What this is
------------
The first *visible* face of ARC. It is NOT a runtime and NOT an implementation:
it renders the seven core client surfaces over a single signed event log, plus
one write path — a single proposal verb routed by the mandate boundary — to make
two claims legible to a human eye —

    every surface is a projection over one closed event log, and
    a mandate is what an agent may sign without re-asking.

Honest scope (deliberate)
-------------------------
  * The log is NOT authored here. It is generated by the real probe
    `examples/end-to-end-demo/flow.py` and reused verbatim — so what the viewer
    shows is real generated data, not a mock.
  * The write path (run_proposals / evaluate) signs with the probe's MOCK scheme,
    and only to show the mandate -> sign/escalate DECISION. It does not address
    the two deferred questions — key custody, and cold-start vs unrooted. The
    key never crosses the proposal boundary; the runtime proposes, the client
    signs. Proposals are scripted, not produced by a live runtime or an MCP wire.
  * The projections are computed by the probe's own fold
    (`project_merchant_standing`), not re-implemented here. The HTML is pure
    presentation; the authority over "what the log means" stays in the probe.
  * This demo's delegation is single-level (one per-purchase AUTHORIZE), so the
    delegation tree is shallow. Multi-level sub-agent spawning is out of scope
    for this log and is left for a later fixture.

Run:  python3 build.py    ->  writes client.html  (open it in a browser)
"""

from __future__ import annotations

import contextlib
import dataclasses
import html
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "end-to-end-demo"))

import flow  # the real probe; reused, not copied

# key id -> display name (presentation only; the keys come from flow.py's parties)
NAMES = {
    "k:human": "human",
    "k:consumer_agent": "consumer-agent",
    "k:merchant": "merchant-agent",
    "k:community": "community",
}


def name(key: str) -> str:
    return NAMES.get(key, key)


def esc(x) -> str:
    return html.escape(str(x))


# ---------------------------------------------------------------------------
# Capture the real generated log (suppress the probe's narration on import-run).
# ---------------------------------------------------------------------------

def capture_log() -> list[flow.Event]:
    with contextlib.redirect_stdout(io.StringIO()):
        ledger = flow.run()
    return ledger.events


def project_at(events: list[flow.Event], upto_predicate: str) -> dict:
    """Fold the log up to and including the first event with this predicate,
    using the probe's own projection (not re-implemented here)."""
    cut = next(i for i, e in enumerate(events) if e.predicate == upto_predicate)
    sub = events[: cut + 1]
    return flow.project_merchant_standing(sub, flow.MERCHANT, flow.CONTEXT)


# ---------------------------------------------------------------------------
# Surface renderers — each returns an HTML fragment, each sourced from the log.
# ---------------------------------------------------------------------------

def render_delegation_tree(events) -> str:
    keys = [e for e in events if e.type == "KEY" and e.predicate == "id.key_register"]
    auth = next(e for e in events if e.type == "AUTHORIZE")
    grantees = sorted({name(e.signer) for e in events if auth.id in e.refs})
    scope = auth.scope or {}
    scope_str = ", ".join(f"{k}={v}" for k, v in scope.items())

    rows = []
    for k in keys:
        nm = name(k.signer)
        rows.append(f'<div class="node"><span class="who">{esc(nm)}</span>'
                    f'<span class="kid">{esc(k.signer)}</span></div>')
        if nm == name(auth.signer):
            for g in grantees:
                rows.append(
                    f'<div class="edge">└─ AUTHORIZE <code>{esc(auth.predicate)}</code> '
                    f'→ <span class="who">{esc(g)}</span>'
                    f'<span class="scope">scope: {esc(scope_str)}</span></div>')
    note = ('<p class="note">Four independently key-rooted participants. The only '
            'delegation edge in this log is one per-purchase AUTHORIZE — '
            'single-level by design of this probe.</p>')
    return "".join(rows) + note


def render_mandate(events) -> str:
    auth = next(e for e in events if e.type == "AUTHORIZE")
    scope = auth.scope or {}
    rows = "".join(f'<div class="kv"><span>{esc(k)}</span><code>{esc(v)}</code></div>'
                   for k, v in scope.items())
    return (
        f'<div class="mandate">'
        f'<div class="kv"><span>granted by</span><code>{esc(name(auth.signer))}</code></div>'
        f'<div class="kv"><span>predicate</span><code>{esc(auth.predicate)}</code></div>'
        f'{rows}'
        f'<div class="kv"><span>refs</span><code>{esc(", ".join(auth.refs))}</code></div>'
        f'</div>'
        f'<p class="note">This is the boundary between what an agent may sign '
        f'<em>without re-asking</em> (in scope) and what must escalate.</p>')


def render_approval_inbox(events, results=()) -> str:
    auth = next(e for e in events if e.type == "AUTHORIZE")
    items = [
        f'<div class="approval resolved">'
        f'<div class="head"><span class="tag ok">RESOLVED</span> '
        f'consumer-agent requested approval for an offer</div>'
        f'<div class="body">the consumer agent could not approve; the human '
        f'reviewed and signed <code>AUTHORIZE {esc(auth.predicate)}</code> '
        f'<span class="evid">[{esc(auth.id)}]</span></div></div>']
    for p, decision, reason, _ev in results:
        if decision == "escalate":
            items.append(
                f'<div class="approval pending">'
                f'<div class="head"><span class="tag warn">PENDING</span> '
                f'{esc(name(p.proposer))} proposed <code>{esc(p.predicate)}</code> '
                f'<span class="origin">origin: runtime</span></div>'
                f'<div class="body">{esc(reason)} — needs a human/root decision</div></div>')
    note = ('<p class="note">The request itself is transport, not a stored event — '
            'only the human\'s AUTHORIZE is on the log. PENDING items are runtime '
            'proposals the boundary would not auto-sign (see the write path below).</p>')
    return "".join(items) + note


def render_commitments(events) -> str:
    preds = {"commerce.offer", "commerce.payment_result", "commerce.fulfillment"}
    items = []
    for e in events:
        if e.predicate in preds:
            summary = ", ".join(f"{k}={v}" for k, v in e.payload.items()
                                if k not in ("context",))
            items.append(
                f'<div class="commit"><div class="head">'
                f'<span class="who">{esc(name(e.signer))}</span> '
                f'<code>{esc(e.predicate)}</code> '
                f'<span class="evid">[{esc(e.id)}]</span></div>'
                f'<div class="body">{esc(summary)}</div></div>')
    return "".join(items)


def render_projection(snapshots) -> str:
    buttons, panels = [], []
    for i, (label, s) in enumerate(snapshots):
        active = " active" if i == 0 else ""
        buttons.append(
            f'<button class="snapbtn{active}" data-snap="{i}">{i+1}</button>')
        rows = (
            f'<div class="kv big"><span>governance_standing</span>'
            f'<code class="gov-{esc(s["governance_standing"])}">'
            f'{esc(s["governance_standing"])}</code></div>'
            f'<div class="kv"><span>advisory_signal</span>'
            f'<code>{esc(s["advisory_signal"])}</code></div>'
            f'<div class="kv"><span>open_disputes</span>'
            f'<code>{esc(s["open_disputes"])}</code></div>'
            f'<div class="kv"><span>outcomes</span>'
            f'<code>+{esc(s["positive_outcomes"])} / -{esc(s["negative_outcomes"])}</code></div>')
        panels.append(
            f'<div class="snap{active}" data-snap="{i}">'
            f'<div class="snaplabel">{esc(label)}</div>{rows}</div>')
    caption = ('<p class="note">Same fold, recomputed at three cuts of the same '
               'log. <strong>governance does not move on the dispute — only on the '
               'ADJUDICATE.</strong> Nothing is stored; each view is recomputed.</p>')
    return (f'<div class="snapnav">snapshot {"".join(buttons)}</div>'
            f'{"".join(panels)}{caption}')


def render_challenge(events) -> str:
    chal = next(e for e in events if e.type == "CHALLENGE")
    adj = next(e for e in events if e.type == "ADJUDICATE")
    return (
        f'<div class="challenge"><span class="tag warn">⚠ CHALLENGE</span> '
        f'<code>{esc(chal.predicate)}</code> by {esc(name(chal.signer))} '
        f'<span class="evid">[{esc(chal.id)}]</span><div class="body">'
        f'{esc(chal.payload.get("reason",""))}</div></div>'
        f'<div class="adjudication"><span class="tag verdict">⚖ ADJUDICATE</span> '
        f'<code>{esc(adj.predicate)}</code> by {esc(name(adj.signer))} '
        f'<span class="evid">[{esc(adj.id)}]</span><div class="body">'
        f'resolves <code>{esc(adj.payload.get("resolves",""))}</code></div></div>'
        f'<p class="note">A CHALLENGE opens a dispute; only an ADJUDICATE '
        f'(referencing it) resolves it and moves commons standing.</p>')


def render_event_log(events, proposed=()) -> str:
    rows = []
    for i, e in enumerate(events):
        rows.append(
            f'<tr data-i="{i}"><td>{i}</td><td class="t-{esc(e.type)}">{esc(e.type)}</td>'
            f'<td>{esc(name(e.signer))}</td><td><code>{esc(e.predicate)}</code></td>'
            f'<td class="evid">{esc(e.id)}</td></tr>')
    for j, e in enumerate(proposed):
        i = len(events) + j
        rows.append(
            f'<tr class="proposed" data-i="{i}"><td>{i}</td>'
            f'<td class="t-{esc(e.type)}">{esc(e.type)}</td>'
            f'<td>{esc(name(e.signer))}</td><td><code>{esc(e.predicate)}</code> '
            f'<span class="tag ok">proposed · auto-signed</span></td>'
            f'<td class="evid">{esc(e.id)}</td></tr>')
    return ('<table class="log"><thead><tr><th>#</th><th>type</th><th>signer</th>'
            '<th>predicate</th><th>id</th></tr></thead><tbody>'
            + "".join(rows) + '</tbody></table>'
            '<div id="inspector"><div class="ins-empty">click an event to inspect '
            'its raw signed form</div></div>')


# ---------------------------------------------------------------------------
# Page assembly.
# ---------------------------------------------------------------------------

CSS = """
:root{--ink:#1d2330;--mut:#6b7280;--line:#e3e6ee;--bg:#f7f8fb;--card:#fff;
--ok:#15803d;--warn:#b45309;--verdict:#6d28d9;--accent:#1f4ed8}
*{box-sizing:border-box}body{margin:0;font:13px/1.5 ui-monospace,SFMono-Regular,
Menlo,Consolas,monospace;color:var(--ink);background:var(--bg)}
header{padding:14px 20px;border-bottom:1px solid var(--line);background:var(--card)}
header h1{margin:0;font-size:15px;letter-spacing:.02em}
header .sub{color:var(--mut);font-size:12px;margin-top:3px}
.grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px;padding:14px}
.col{display:flex;flex-direction:column;gap:14px}
.card{background:var(--card);border:1px solid var(--line);border-radius:8px;
overflow:hidden}
.card>h2{margin:0;padding:9px 12px;font-size:12px;letter-spacing:.04em;
text-transform:uppercase;color:var(--mut);border-bottom:1px solid var(--line);
background:#fbfcfe}
.card>.in{padding:12px}
.note{color:var(--mut);font-size:11.5px;margin:10px 0 0;line-height:1.45}
code{background:#f0f2f7;padding:1px 5px;border-radius:4px;font-size:12px}
.who{font-weight:600}.kid{color:var(--mut);margin-left:8px;font-size:11px}
.node{padding:3px 0}.edge{padding:3px 0 3px 16px;color:#374151}
.edge .scope{display:block;color:var(--mut);font-size:11px;padding-left:18px}
.kv{display:flex;justify-content:space-between;gap:10px;padding:4px 0;
border-bottom:1px dashed var(--line)}.kv:last-child{border:0}
.kv span{color:var(--mut)}.kv.big code{font-size:13px}
.approval,.commit,.challenge,.adjudication{border:1px solid var(--line);
border-radius:6px;padding:9px;margin-bottom:8px}
.approval .head,.commit .head{font-weight:600;margin-bottom:4px}
.body{color:#374151}.evid{color:var(--mut);font-size:11px}
.tag{font-size:10px;font-weight:700;padding:1px 6px;border-radius:10px;
letter-spacing:.05em}.tag.ok{background:#dcfce7;color:var(--ok)}
.tag.warn{background:#fef3c7;color:var(--warn)}
.tag.verdict{background:#ede9fe;color:var(--verdict)}
.approval.pending{border-color:#f5d488;background:#fffdf5}
.origin{color:var(--mut);font-size:11px;font-weight:400;margin-left:6px}
.card.band>h2{color:var(--accent)}
.prop{border:1px solid var(--line);border-radius:6px;padding:9px 11px;margin-bottom:9px}
.prop .head{font-weight:600}.prop .ctx{color:var(--mut);font-weight:400}
.prop .intent{color:var(--mut);font-size:11.5px;margin:3px 0 6px}
.prop .decision{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.prop .route{color:var(--mut);font-size:11px;margin-left:auto}
table.log tr.proposed{background:#f3fbf5}table.log tr.proposed:hover{background:#e6f6ec}
.snapnav{color:var(--mut);margin-bottom:10px}
.snapbtn{font:inherit;border:1px solid var(--line);background:#fff;width:26px;
height:26px;border-radius:6px;margin-left:5px;cursor:pointer}
.snapbtn.active{background:var(--accent);color:#fff;border-color:var(--accent)}
.snap{display:none}.snap.active{display:block}
.snaplabel{font-size:11.5px;color:var(--mut);margin-bottom:6px;font-style:italic}
.gov-in_good_standing{color:var(--ok)}.gov-warned{color:var(--warn)}
.full{padding:0 14px 18px}
table.log{width:100%;border-collapse:collapse;background:var(--card);
border:1px solid var(--line);border-radius:8px;overflow:hidden}
table.log th,table.log td{text-align:left;padding:6px 10px;
border-bottom:1px solid var(--line);font-size:12px}
table.log th{color:var(--mut);text-transform:uppercase;font-size:10.5px;
letter-spacing:.04em;background:#fbfcfe}
table.log tbody tr{cursor:pointer}table.log tbody tr:hover{background:#f3f6ff}
table.log tbody tr.sel{background:#e8efff}
.t-KEY{color:#475569}.t-ATTEST{color:#0369a1}.t-AUTHORIZE{color:#15803d}
.t-CHALLENGE{color:#b45309}.t-ADJUDICATE{color:#6d28d9}
#inspector{margin-top:10px;background:#0f172a;color:#e2e8f0;border-radius:8px;
padding:12px;font-size:11.5px;white-space:pre;overflow:auto;max-height:280px}
.ins-empty{color:#64748b}
"""

JS = """
const EVENTS = JSON.parse(document.getElementById('arc-data').textContent);
document.querySelectorAll('.snapbtn').forEach(b=>b.onclick=()=>{
  const i=b.dataset.snap;
  document.querySelectorAll('.snapbtn').forEach(x=>x.classList.toggle('active',x===b));
  document.querySelectorAll('.snap').forEach(p=>p.classList.toggle('active',p.dataset.snap===i));
});
document.querySelectorAll('table.log tbody tr').forEach(tr=>tr.onclick=()=>{
  document.querySelectorAll('table.log tbody tr').forEach(x=>x.classList.remove('sel'));
  tr.classList.add('sel');
  const e=EVENTS[+tr.dataset.i];
  document.getElementById('inspector').textContent=JSON.stringify(e,null,2);
});
"""


# ---------------------------------------------------------------------------
# The write path — one proposal verb, and the boundary that routes it.
# A BYO runtime PROPOSES; the ARC client checks the active mandate and either
# auto-signs (in scope, no human) or escalates (out of scope -> a human/root).
# The key never crosses the proposal boundary; signing happens here, not there.
# ---------------------------------------------------------------------------

@dataclasses.dataclass(frozen=True)
class Proposal:
    proposer: str          # key id of the mandated party, acting via a BYO runtime
    type: str
    predicate: str
    payload: dict
    intent: str


def evaluate(p: Proposal, mandate) -> tuple[str, str]:
    """The ARC client boundary. -> (decision, reason); decision in {auto_sign, escalate}."""
    scope = mandate.scope or {}
    # invariant: an AUTHORIZE can never be auto-signed by the agent it empowers —
    # an agent cannot widen its own mandate (no self-elevation).
    if p.type == "AUTHORIZE":
        return "escalate", "an agent cannot sign its own mandate — only root grants authority"
    ctx_ok = p.payload.get("context") == scope.get("context")
    amount = p.payload.get("amount_krw")
    amount_ok = amount is None or amount <= scope.get("max_total_krw", 0)
    if ctx_ok and amount_ok:
        return "auto_sign", "within mandate scope — signed without re-asking the human"
    if not ctx_ok:
        return "escalate", (f"context {p.payload.get('context')!r} is outside the "
                            f"mandate context {scope.get('context')!r}")
    return "escalate", f"amount {amount} exceeds the mandate ceiling {scope.get('max_total_krw')}"


def run_proposals(events) -> tuple[list, list]:
    mandate = next(e for e in events if e.type == "AUTHORIZE")
    proposer = next((e.signer for e in events if mandate.id in e.refs), mandate.signer)
    proposals = [
        Proposal(proposer, "ATTEST", "rep.outcome",
                 {"result": "positive", "context": "lunch"},
                 "log a positive outcome within the authorized lunch context"),
        Proposal(proposer, "ATTEST", "commerce.payment_result",
                 {"result": "confirmed", "amount_krw": 20000, "context": "lunch"},
                 "pay 20000 KRW for a lunch order"),
        Proposal(proposer, "AUTHORIZE", "consent.approval",
                 {"context": "lunch"},
                 "grant itself a wider mandate"),
    ]
    results, signed = [], []
    for p in proposals:
        decision, reason = evaluate(p, mandate)
        ev = None
        if decision == "auto_sign":
            ev = flow.make(p.type, p.proposer, p.predicate, "2026-06-08T10:12:00Z",
                           payload=dict(p.payload))
            signed.append(ev)
        results.append((p, decision, reason, ev))
    return results, signed


def render_proposal_flow(results) -> str:
    badges = {"auto_sign": ("AUTO-SIGNED", "ok", "→ event log"),
              "escalate": ("ESCALATED", "warn", "→ approval inbox")}
    rows = []
    for p, decision, reason, ev in results:
        label, cls, route = badges[decision]
        amt = p.payload.get("amount_krw")
        amt_s = f" {amt} KRW" if amt is not None else ""
        evid = f' <span class="evid">[{esc(ev.id)}]</span>' if ev else ""
        rows.append(
            f'<div class="prop"><div class="head">'
            f'<span class="who">{esc(name(p.proposer))}</span> · '
            f'<code>{esc(p.type)} {esc(p.predicate)}</code>{esc(amt_s)} '
            f'<span class="ctx">({esc(p.payload.get("context",""))})</span></div>'
            f'<div class="intent">intent: {esc(p.intent)}</div>'
            f'<div class="decision"><span class="tag {cls}">{label}</span> '
            f'{esc(reason)}{evid} <span class="route">{esc(route)}</span></div></div>')
    note = ('<p class="note">One verb — <code>propose_event(type, payload)</code> — for '
            'every type; a BYO runtime proposes, the boundary routes. The key never '
            'crosses this line. Signing here reuses the probe\'s mock scheme; '
            '<em>where</em> keys live (custody) is still out of scope. The base '
            'projection is left unchanged — this panel is the write path, not the read.</p>')
    return "".join(rows) + note


def build_html(events, snapshots, results, signed) -> str:
    data = json.dumps([dataclasses.asdict(e) for e in (list(events) + list(signed))],
                       default=list)
    card = lambda t, b: f'<div class="card"><h2>{t}</h2><div class="in">{b}</div></div>'
    left = card("delegation tree", render_delegation_tree(events)) + \
        card("mandate viewer", render_mandate(events))
    mid = card("approval inbox", render_approval_inbox(events, results)) + \
        card("signed commitments", render_commitments(events))
    right = card("projection viewer", render_projection(snapshots)) + \
        card("challenge / adjudication", render_challenge(events))
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ARC reference client</title><style>{CSS}</style></head><body>
<header><h1>ARC reference client</h1>
<div class="sub">{len(events)} generated events + one proposal verb ·
every panel folds over the one log · the boundary signs, the key never leaves it</div></header>
<div class="grid">
<div class="col">{left}</div>
<div class="col">{mid}</div>
<div class="col">{right}</div>
</div>
<div class="full"><div class="card band"><h2>live proposal — the write path (the boundary decides)</h2>
<div class="in">{render_proposal_flow(results)}</div></div></div>
<div class="full"><div class="card"><h2>event log — the one source of truth</h2>
<div class="in">{render_event_log(events, signed)}</div></div></div>
<script id="arc-data" type="application/json">{data}</script>
<script>{JS}</script>
</body></html>"""


def main() -> None:
    events = capture_log()
    snapshots = [
        ("after fulfillment", project_at(events, "commerce.fulfillment")),
        ("after dispute", project_at(events, "rep.outcome")),
        ("after adjudication", project_at(events, "gov.warning")),
    ]
    results, signed = run_proposals(events)
    out = os.path.join(HERE, "client.html")
    with open(out, "w") as f:
        f.write(build_html(events, snapshots, results, signed))
    print(f"captured {len(events)} signed events from the end-to-end-demo probe")
    for label, s in snapshots:
        print(f"  [{label}] governance={s['governance_standing']} "
              f"open_disputes={s['open_disputes']}")
    print("proposal routing through the boundary:")
    for p, decision, reason, ev in results:
        evid = f" [{ev.id}]" if ev else ""
        print(f"  {decision:9} {p.type} {p.predicate}{evid} — {reason}")
    # the auto-signed proposals verify against the same log they extend
    flow.verify_log(events + signed)
    print(f"wrote {os.path.relpath(out)} — open it in a browser")


if __name__ == "__main__":
    main()
